name: zimbo
description: Zimbo

publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Design
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  lottie: ^1.3.0
  google_fonts: ^3.0.0 
  flutter_svg: ^1.0.0 
  dotted_border: ^2.0.0+2
  auto_size_text: ^3.0.0
  flutter_native_splash: ^2.1.6

  # for MVC
  stacked: ^2.3.8
  get_it: ^7.2.0
  provider: ^6.0.1

  # System
  shared_preferences: ^2.0.9

  # Api calls
  dio: ^4.0.6

  # Auth
  sign_in_with_apple: ^4.0.0
  google_sign_in: ^5.3.0
  flutter_login_facebook: ^1.5.0+1
  firebase_core: ^1.19.2
  firebase_messaging: ^12.0.0
  flutter_local_notifications: ^9.7.0

  # Utils
  nb_utils: ^4.4.10
  bot_toast: ^4.0.2
  url_launcher: ^6.0.17
  uni_links: ^0.5.1
  share_plus: ^4.0.4
  rxdart: ^0.27.4


  # More
  fast_barcode_scanner: ^1.1.4
  mobile_scanner: ^2.0.0
  expandable: ^5.0.1
  intl: ^0.17.0 
  image_picker: ^0.8.4+4
  flutter_multi_formatter: ^2.5.1
  weekday_selector: ^1.0.0
  group_button: ^5.0.0
  permission_handler: ^9.2.0
  bottom_picker: ^1.8.0
  
  # Payment
  in_app_purchase: ^3.0.6

  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/images/
  - assets/images/png/
  - assets/images/svg/
  - assets/images/json/
