name: zimbo
description: Zimbo

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Design
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  lottie: ^1.2.1
  google_fonts: ^2.1.0 
  flutter_svg: ^1.0.0 
  dotted_border: ^2.0.0+2

  # for MVC
  stacked: ^2.2.7+1
  get_it: ^7.2.0
  provider: ^6.0.1

  # System
  shared_preferences: ^2.0.9
  device_info_plus: ^3.2.0
  package_info_plus: ^1.3.0

  # Api calls
  dio: ^4.0.4

  # Auth
  google_sign_in: ^5.2.4
  flutter_login_facebook: ^1.4.1
  firebase_auth: ^3.3.13
  firebase_core: ^1.14.0
  cloud_firestore: ^3.1.11
  firebase_storage: ^10.2.11
  firebase_messaging: ^11.2.12
  flutter_local_notifications: ^9.4.0

  # Utils
  nb_utils: ^4.4.10
  bot_toast: ^4.0.1
  url_launcher: ^6.0.17
  uni_links: ^0.5.1


  # More
  fast_barcode_scanner: ^1.1.4
  qr_code_scanner: ^0.7.0
  expandable: ^5.0.1
  intl: ^0.17.0
  image_picker: ^0.8.4+4
  flutter_multi_formatter: ^2.5.1
  stripe_sdk: ^5.0.0-nullsafety.1
  weekday_selector: ^1.0.0
  group_button: ^4.6.0
  permission_handler: ^9.2.0

  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.2

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/images/
  - assets/images/png/
  - assets/images/svg/
  - assets/images/json/
